### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by aaroniker** [aaroniker/rokket#2]
##### Aaron
- [x] Basic PHP classes
- [x] User login
- [x] Remember login
- [x] Multi language support
- [x] Cache management
- [x] generate .css file from .less
- [x] Design + HTML, CSS, jQuery (responsive)
- [x] User management + permissions
- [x] Server management (+ phpseclib)

**Comment by aaroniker** [comment]
[ ] Re-Design necessary (usability)

**Comment by aaroniker** [comment]
Some things for first release:

- [ ] Installer
- [ ] Logs
- [ ] Add more games
- [ ] New website (70% done)
- [ ] Check port before adding a server (duplicate)
- [ ] Test permissions

**Comment by aaroniker** [comment]
- [ ] General Validation

**Comment by aaroniker** [comment]
- [x] New dashboard

**Comment by aaroniker** [comment]
- [ ] Check for necessary dependencies (https://github.com/dgibbs64/linuxgsm/wiki/Dependencies)

**Comment by aaroniker** [comment]
Website at 90%

**Comment by aaroniker** [comment]
New Website done: http://rokket.info
